### ISSUE TITLE
Run commands directly through docker container

### ISSUE THREAD

**Issue by Wetitpig** [Rudloff/termux-docker-image#6]
Can we run commands directly like:
`docker run -it rudloff/termux apt update`?

Thanks

**Comment by Rudloff** [comment]
What is your issue exactly?
You can run commands like with any Docker container: `docker run rudloff/termux apt update`
You can also run multiple commands like this: `docker run rudloff/termux bash -c "apt update && apt install screenfetch && screenfetch"`

**Comment by Wetitpig** [comment]
Thanks
